"""initial schema

Revision ID: 24333977a264
Revises: 
Create Date: 2026-09-16 20:03:29.940491+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24333977a264'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False, comment='Same UUID as auth.users.id (supplied by Supabase Auth)'),
    sa.Column('display_name', sa.String(length=255), nullable=True, comment='User-chosen display name'),
    sa.Column('avatar_url', sa.Text(), nullable=True, comment="URL to the user's avatar image"),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_profiles_display_name', 'profiles', ['display_name'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_track_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('artist', sa.String(length=500), nullable=False),
    sa.Column('album', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('artwork_url', sa.Text(), nullable=True),
    sa.Column('license_url', sa.Text(), nullable=True),
    sa.Column('license_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'provider_track_id', name='uk_favorites_user_provider_track')
    )
    op.create_index('idx_favorites_user_created_at', 'favorites', ['user_id', 'created_at'], unique=False)
    op.create_table('playlists',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Playlist primary key'),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False, comment='Owning profile (profiles.id)'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='User-visible playlist name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional free-text description'),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Reserved for future sharing support'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_playlists_user_created_at', 'playlists', ['user_id', 'created_at'], unique=False)
    op.create_table('recently_played',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_track_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('artist', sa.String(length=500), nullable=False),
    sa.Column('album', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('artwork_url', sa.Text(), nullable=True),
    sa.Column('license_url', sa.Text(), nullable=True),
    sa.Column('license_name', sa.String(length=100), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the play event occurred'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recently_played_user_played_at', 'recently_played', ['user_id', 'played_at'], unique=False)
    op.create_index('idx_recently_played_user_provider_track', 'recently_played', ['user_id', 'provider', 'provider_track_id'], unique=False)
    op.create_table('playlist_tracks',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('playlist_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False, comment='Zero-based ordering within the playlist'),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_track_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('artist', sa.String(length=500), nullable=False),
    sa.Column('album', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('artwork_url', sa.Text(), nullable=True),
    sa.Column('license_url', sa.Text(), nullable=True),
    sa.Column('license_name', sa.String(length=100), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_playlist_tracks_position_non_negative'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playlist_id', 'position', deferrable=True, initially='DEFERRED', name='uk_playlist_tracks_playlist_position'),
    sa.UniqueConstraint('playlist_id', 'provider', 'provider_track_id', name='uk_playlist_tracks_playlist_track')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_tracks')
    op.drop_index('idx_recently_played_user_provider_track', table_name='recently_played')
    op.drop_index('idx_recently_played_user_played_at', table_name='recently_played')
    op.drop_table('recently_played')
    op.drop_index('idx_playlists_user_created_at', table_name='playlists')
    op.drop_table('playlists')
    op.drop_index('idx_favorites_user_created_at', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index('idx_profiles_display_name', table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
